"""empty message

Revision ID: 67b35216769b
Revises: f53607cb9e6e
Create Date: 2023-09-12 16:38:17.829978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b35216769b'
down_revision = 'f53607cb9e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_animals_species_id_species'), 'species', ['species_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_animals_species_id_species'), type_='foreignkey')
        batch_op.drop_column('species_id')

    op.drop_table('species')
    # ### end Alembic commands ###
